#!/bin/bash

module load dials/nightly
. /dls/science/groups/scisoft/DIALS/Python3/setup 

cat <<EOF >README.md
## Python3 compatibility tests

module | result
--- | ---
EOF

for repository in $(libtbx.list_modules | sort)
do
  echo $repository
  RP=$(libtbx.find_in_repositories $repository)
  python3 -m compileall -x "\.git" -q $RP | perl -pe "s#$RP#$repository#" > $repository.log

  FAILS=$(grep "^\*\*\*" $repository.log | wc -l)
  if [ "$FAILS" == "0" ]; then
    echo "$repository | :white_check_mark:&nbsp; all OK" >> README.md
  else
    echo "$repository | :red_circle:&nbsp; [$FAILS files]($repository.log) violate python3 syntax" >> README.md
  fi
done

git add *.md *.log
git commit -m "update"
git push
